apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argo-ingress-main
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: argo-ingress.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: argo-ingress-stable
            port:
              number: 80
