apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: argo-ingress
  labels:
    app: argo-ingress
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: argo-ingress
  template:
    metadata:
      labels:
        app: argo-ingress
    spec:
      containers:
        - name: argo-ingress
          image: "argo-ingress:3" 
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
  strategy:
    canary: # Mudou de 'ingress' para 'canary'
      stableService: argo-ingress-stable
      canaryService: argo-ingress-canary
      trafficRouting:
        nginx:
          stableIngress: argo-ingress-main # Nome do Ingress que criamos acima
      steps:
        - setWeight: 25
        - pause: {}
        - setWeight: 50
        - pause: { duration: 1m }
        - setWeight: 85
        - pause: {}
        - setWeight: 100